### ISSUE TITLE
make error 

### ISSUE THREAD

**Issue by tatecarson** [snappizz/broken-physical-models#1]
When I go to make on a mac I get this error: 

`/Users/tatecarson/Downloads/broken-physical-models-master/source/dwgs.h:4:10: fatal error: 
      'SC_PlugIn.h' file not found
# include "SC_PlugIn.h"

```
     ^
```

1 error generated.
make[2]: **\* [CMakeFiles/GlitchPiano.dir/source/GlitchPiano.cpp.o] Error 1
make[1]: **\* [CMakeFiles/GlitchPiano.dir/all] Error 2
make: **\* [all] Error 2
`

Why do you think that is? Is there a part i'm missing?

**Comment by nhthn** [comment]
Have you set SC_PATH in cmake?

**Comment by tatecarson** [comment]
I did cmake -DSC_PATH="/Applications/SuperCollider/" just now and I get the same result. Is that not the right path? Do I also need to do it somewhere else?

**Comment by tatecarson** [comment]
Figured it out. It might be helpful to mention in the readme that the actual supercollider source is needed and to point the directory to the include folder, for people who might have never done this before. Thanks for your work, sounds great!

**Comment by nhthn** [comment]
Yes, `/path/to/supercollider/source/` is a bit ambiguous. I'll change it.

I'm flattered by your interest. I haven't gotten any crashes or bad values out of this ugen yet, so I'd say it's no less stable than its unglitched version. Still, I would probably test it a lot before a live performance.
